#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
from pathlib import Path

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# Remove route configuration
p = Path(f'configs/{data["instance"]}-route.yml')
p.unlink(missing_ok=True)
