#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import agent
import sys
import urllib.request
from get_route import get_route


api_path = os.environ["API_PATH"]

data = json.load(sys.stdin)

# Get the list of routers keys
try:
    with urllib.request.urlopen(f'http://127.0.0.1/{api_path}/api/http/routers') as res:
        traefik_routes = json.load(res)
except urllib.error.URLError as e:
    raise Exception(f'Error reaching traefik daemon: {e.reason}')

# Gernerate the list of routes
routes = [ route['name'].removesuffix('-https@file') for route in traefik_routes if route['name'].endswith('-https@file') ]

# Don't list custom `/cluster-admin` route
routes = list(filter(lambda route: route != "ApiServer", routes))

if data != None and data.get('expand_list'):
    routes = [ get_route({'instance': route}) for route in routes ]

json.dump(routes, fp=sys.stdout)
