#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import agent
import sys
import urllib.request

from custom_certificate_manager import list_custom_certificates
from get_certificate import get_certificate


api_path = os.environ["API_PATH"]

data = json.load(sys.stdin)

# Get the list of routers keys
try:
    with urllib.request.urlopen(f'http://127.0.0.1/{api_path}/api/http/routers') as res:
        traefik_routes = json.load(res)
except urllib.error.URLError as e:
    raise Exception(f'Error reaching traefik daemon: {e.reason}') from e

# Gernerate the list of certificates
certificates = [ route['name'].removeprefix('certificate-').removesuffix('@file') for route in traefik_routes
        if route['name'].startswith('certificate-') and route['name'].endswith('@file') ]

if data != None and data.get('expand_list'):
    certificates = [ get_certificate({'fqdn': certificate}) for certificate in certificates ]

certificates = certificates + list_custom_certificates()

json.dump(certificates, fp=sys.stdout)
