#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import conf_helpers

def main():
    curconf = conf_helpers.parse_yaml_config("traefik.yaml")
    try:
        proxies = list(set(
            curconf['entryPoints']['http']['forwardedHeaders']["trustedIPs"] +
            curconf['entryPoints']['https']['forwardedHeaders']["trustedIPs"]
        ))
    except KeyError:
        proxies = []
    response = {
        "proxies": proxies,
        "depth": int(os.getenv("PROXIES_DEPTH", 0))
    }
    json.dump(response, fp=sys.stdout)

if __name__ == "__main__":
    main()
