#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os

data = json.load(sys.stdin)

agent.set_env("ACME_SERVER_URL", data["url"])
