#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os

res = { "url": os.getenv('ACME_SERVER_URL') }

print(json.dumps(res))
