#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os
import conf_helpers

def main():
    curconf = conf_helpers.parse_yaml_config("traefik.yaml")
    try:
        url = curconf['certificatesResolvers']['acmeServer']['acme']["caServer"]
    except KeyError:
        url = "https://acme-v02.api.letsencrypt.org/directory"
    try:
        email = curconf['certificatesResolvers']['acmeServer']['acme']["email"] or ""
    except KeyError:
        email = ""
    try:
        if curconf['certificatesResolvers']['acmeServer']['acme']['httpChallenge']['entryPoint'] == "https":
            challenge = "TLS-ALPN-01"
        elif curconf['certificatesResolvers']['acmeServer']['acme']['httpChallenge']['entryPoint'] == "http":
            challenge = "HTTP-01"
        else:
            challenge = "HTTP-01"
    except KeyError:
        challenge = "HTTP-01"
    response = {
        "url": url,
        "email": email,
        "challenge": challenge,
    }
    json.dump(response, fp=sys.stdout)

if __name__ == "__main__":
    main()
