#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os.path
import sys
import agent
from glob import glob

dump = {'routes':{}, 'uploaded_certificates': {}}

# custom routes
for cfile in glob(f'configs/*.yml'):
    route = os.path.basename(cfile).removesuffix('.yml')
    if os.path.isfile(f'manual_flags/{route}'):
        with open(cfile, 'r') as fp:
            dump['routes'][route] = fp.read()

# uploaded certificates
for key in glob(f'custom_certificates/*.key'):
    cn = os.path.basename(key).removesuffix('.key')
    if cn not in dump['uploaded_certificates']:
        dump['uploaded_certificates'][cn] = {'crt': '', 'key': ''}
    with open(key, 'r') as fsk:
        dump['uploaded_certificates'][cn]['key'] = fsk.read()
    with open(f'custom_certificates/{cn}.crt', 'r') as fsc:
        dump['uploaded_certificates'][cn]['crt'] = fsc.read()

# acme certificates are not saved because will be recreated by traefik on first start

json.dump(dump, fp=sys.stdout)
