#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

uuid =  os.popen("uuidgen")
agent.set_env('API_PATH', uuid.read())
