#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

LOG_LEVEL=${LOG_LEVEL:-INFO}
ACME_SERVER_URL=${ACME_SERVER_URL:-https://acme-v02.api.letsencrypt.org/directory}

cat >&${AGENT_COMFD} <<EOF
set-env LE_EMAIL ${LE_EMAIL}
set-env LOG_LEVEL ${LOG_LEVEL}
set-env ACME_SERVER_URL ${ACME_SERVER_URL}
dump-env
EOF

cat >traefik.yaml <<EOF 
defaultEntryPoints:
  - http
  - https

file: {}

log:
  level: $LOG_LEVEL

accessLog: {}

entryPoints:
  http:
   address: ":80"
  https:
   address: ":443"

providers:
  redis:
    rootKey: "${AGENT_ID}/kv"
    endpoints:
      - "127.0.0.1:6379"
  file:
    directory: "/etc/traefik/configs"

tls:
  certResolver: acmeServer
  options: {}

certificatesResolvers:
  acmeServer:
    acme:
      email: ${LE_EMAIL}
      caServer: ${ACME_SERVER_URL}
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: http
      tlsChallenge: false

ping:
  manualRouting: true

api: {}
EOF
