#!/bin/bash

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -e    # exit immediately if an error occurs
exec 1>&2 # ensure any output is sent to stderr

#
# Allow other modules to call our *-route actions by requiring the "routeadm" role
#
routeadm_actions=(
    delete-route
    set-route
    get-route
    list-routes
)
redis-exec SADD "${AGENT_ID}/roles/routeadm" "${routeadm_actions[@]}"

#
# Allow other modules to call our *-certificate actions by requiring the "certadm" role
#
certadm_actions=(
    delete-certificate
    set-certificate
    get-certificate
    list-certificates
)
redis-exec SADD "${AGENT_ID}/roles/certadm" "${certadm_actions[@]}"

#
# Grant all actions
#
redis-exec SADD "${AGENT_ID}/roles/fulladm" "${certadm_actions[@]}" "${routeadm_actions[@]}"

# Allow module to call `set-route` on himself
redis-exec SADD "${AGENT_ID}/roles/selfadm" "set-route"
