#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# Redirect any output to the journal (stderr)
exec 1>&2

#
# Create file provider configurations directory
#
mkdir -p configs

# Create uploaded certificates folder
mkdir -p custom_certificates

# Create acme storage folder
mkdir -p acme

# Enable and start the services
systemctl --user enable --now traefik.service
