#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import time
from get_route import get_route

retry = 0

while get_route({'instance': 'ApiServer'}, ignore_error = True).get('instance') != "ApiServer" and retry <= 10:
    retry += 1
    time.sleep(1)
