#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Delete a Let's Encrypt certificate
# Input example:
#
#  {"fqdn": "example.com"}
#

import json
import sys
import os
import agent

from custom_certificate_manager import delete_custom_certificate, list_custom_certificates

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Try to delete uploaded certificate
custom_certificate = False
for cert in list_custom_certificates():
    if cert.get('fqdn') == data['fqdn']:
        delete_custom_certificate(data['fqdn'])
        custom_certificate = True

# Try to delete the route for obtained certificate
if not custom_certificate:
    cert_path = f'configs/certificate-{data["fqdn"]}.yml'
    if os.path.isfile(cert_path):
        os.unlink(cert_path)

# Output valid JSON
print("true")
