#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import time
from get_certificate import get_certificate

data = json.load(sys.stdin)
retry = 0

while get_certificate(data).get('fqdn') == data['fqdn'] and retry <= 10:
    retry += 1
    time.sleep(1)
