#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import agent
import sys
import base64
import cert_helpers


def main():
    request = json.load(sys.stdin)
    bcert = base64.b64decode(request["certFile"])
    changed_dns_names = cert_helpers.extract_certified_names(bcert)
    notify_certificate_changed_event(changed_dns_names)

def notify_certificate_changed_event(changed_dns_names):
    rdb = agent.redis_connect(privileged=True)
    rdb.publish(f"{os.environ['AGENT_ID']}/event/certificate-changed", json.dumps({
        "node_id": int(os.environ['NODE_ID']),
        "module_id": os.environ['MODULE_ID'],
        "names": list(changed_dns_names),
    }))

if __name__ == "__main__":
    main()
