#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Request a let's encrypt certificate
# Input example:
#  {"fqdn": "example.com"}
#

import json
import sys
import os
import uuid
import yaml
from custom_certificate_manager import list_custom_certificates

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)


#Don't request a certificate if it is already uploaded
for cert in list_custom_certificates():
    if cert.get('fqdn') == data['fqdn']:
        sys.exit(0)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Setup HTTP ans HTTPS routers
path = uuid.uuid4()
router = {
        'entrypoints':  "https",
        'service': "ping@internal",
        'rule' :  f'Host(`{data["fqdn"]}`) && Path(`/{path}`)',
        'priority': '1',
        'tls': { 'domains': [{'main': data["fqdn"]}], 'certresolver': "acmeServer"}
        }

# Write configuration file
config = {"http": {"routers": {f'certificate-{data["fqdn"]}': router}}}
with open(f'configs/certificate-{data["fqdn"]}.yml', 'w') as fp:
    fp.write(yaml.safe_dump(config, default_flow_style=False, sort_keys=False, allow_unicode=True))
