#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import cert_helpers
import agent
import datetime

def main():
    tstart = datetime.datetime.now(datetime.UTC)
    request = json.load(sys.stdin)
    if cert_helpers.validate_certificate_names(request['fqdn'], timeout=request.get('sync_timeout', 30)):
        cert_helpers.add_default_certificate_name(request['fqdn'])
        json.dump({"obtained": True}, fp=sys.stdout)
    else:
        acme_error = cert_helpers.traefik_last_acme_error_since(tstart)
        for errline in acme_error.split('\n'):
            print(agent.SD_ERR + errline, file=sys.stderr)
        # NOTE: this action does not return the usual validation-failed format
        json.dump({"obtained": False}, fp=sys.stdout)
        exit(2)

if __name__ == "__main__":
    main()
