#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

import json
import sys
import time
import agent
from get_certificate import get_certificate

data = json.load(sys.stdin)
retry = 0
certificate = {}

sync_timeout = data['sync_timeout'] if data.get('sync_timeout') is not None else 120

while get_certificate(data).get('fqdn') != data['fqdn'] and retry <= 10:
    retry += 1
    time.sleep(1)

certificate['obtained'] = get_certificate(data).get('obtained')

if certificate['obtained'] is False and data.get('sync') is not None and data['sync'] is True:
    retry = 0
    while certificate['obtained'] != True and retry < sync_timeout:
      agent.set_progress(round((retry*100)/sync_timeout))
      certificate['obtained'] = get_certificate(data).get('obtained')
      retry += 1
      time.sleep(1)

json.dump(certificate, fp=sys.stdout)

if data.get('sync') is not None and certificate['obtained'] is False:
    exit(2)
