#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Create static configuration, ignore warnings
~/.config/actions/create-module/10expandconfig 2>/dev/null
~/.config/actions/create-module/50create 2>/dev/null
# Convert existing configuration to yaml
~/.config/bin/redis2yml
