#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import ipaddress

def main():
    agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all
    request = json.load(sys.stdin)
    if "ip_allowlist" in request:
        for ipvalue in request['ip_allowlist']:
            # Check if ipvalue is a string representing IPv4, IPv6, or
            # CIDR:
            try:
                if '/' in ipvalue:
                    # CIDR validation
                    ipaddress.ip_network(ipvalue, strict=False)
                else:
                    # IP validation
                    ipaddress.ip_address(ipvalue)
            except ValueError:
                agent.set_status('validation-failed')
                json.dump([{'field':'ip_allowlist','parameter':'ip_allowlist','value': ipvalue,'error':'bad_ip_address'}], fp=sys.stdout)
                sys.exit(3)

if __name__ == "__main__":
    main()
