#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

if "host" in data and "path" not in data:
    if data["host"] == '127.0.0.1' or data["host"] == 'localhost':
        json.dump([{'field':'host','parameter':'host','value': data["host"],'error':'host_is_not_valid_not_localhost'}], fp=sys.stdout)
        sys.exit(2)
        