#!/usr/bin/env python3

#
# Copyright (C) 2021 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

#
# Create a virtual host configuration
# Input example:
#  {"instance": "module1", "url": "http://127.0.0.0:2000", "path": "/foo", "http2https": true}
#

import json
import sys
import os
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

agent_id = os.getenv("AGENT_ID", "")
if not agent_id:
    raise Exception("AGENT_ID not found inside the environemnt")

# Connect to redis
r = agent.redis_connect(privileged=True).pipeline()

# Prepare common key prefix
prefix=f'{agent_id}/kv/http'
router=f'{prefix}/routers/{data["instance"]}-http'
router_s=f'{prefix}/routers/{data["instance"]}-https'
middlewares=f'{prefix}/middlewares'

# Setup HTTP ans HTTPS routers
r.set(f'{prefix}/services/{data["instance"]}/loadBalancer/servers/0/url', data["url"])
r.set(f'{router}/service', data["instance"])
r.set(f'{router}/entrypoints', "http,https")
r.set(f'{router_s}/entrypoints', "http,https")

# Remove trailing slash if present
if data.get("path") is not None:
    if data["path"] != "/":
        path = data["path"].rstrip("/")
        path_prefix = path + "/"
    else:
        path_prefix = path = "/"

if data.get("host") is not None and data.get("path") is not None:
    #http routes
    r.set(f'{router_s}/rule', f'Host(`{data["host"]}`) && (Path(`{path}`) || PathPrefix(`{path_prefix}`))')
    r.set(f'{router_s}/priority', '3')
    #https routes
    r.set(f'{router}/rule', f'Host(`{data["host"]}`) && (Path(`{path}`) || PathPrefix(`{path_prefix}`))')
    r.set(f'{router}/priority', '3')
elif data.get("host") is not None:
    #http routes
    r.set(f'{router}/rule', f'Host(`{data["host"]}`)')
    r.set(f'{router}/priority', '2')
    #https routes
    r.set(f'{router_s}/rule', f'Host(`{data["host"]}`)')
    r.set(f'{router_s}/priority', '2')
else:
    #http routes
    r.set(f'{router}/rule', f'Path(`{path}`) || PathPrefix(`{path_prefix}`)')
    r.set(f'{router}/priority', '1')
    #https routes
    r.set(f'{router_s}/rule', f'Path(`{path}`) || PathPrefix(`{path_prefix}`)')
    r.set(f'{router_s}/priority', '1')
    r.set(f'{router_s}/priority', '1')

r.set(f'{router_s}/tls', "true")
if data.get("host") is not None:
    r.set(f'{router_s}/tls/domains/0/main', data["host"])
else:
    r.delete(f'{router_s}/tls/domains/0/main')

r.set(f'{router_s}/service', data["instance"])


# Enable or disable Let's Encrypt certificate
if data.get("host") is not None:
    if data["lets_encrypt"]:
        r.set(f'{router_s}/tls/certresolver', "acmeServer")
    else:
        r.delete(f'{router_s}/tls/certresolver')

# Enable or disable HTTP 2 HTTPS redirection
if data["http2https"]:
    r.set(f'{router}/middlewares/0', "http2https-redirectscheme")
else:
    r.delete(f'{router}/middlewares/0')

# Strip the path from the request
if data.get("strip_prefix"):
    r.set(f'{middlewares}/{data["instance"]}-stripprefix/stripPrefix/prefixes/0', f'{path}')
    r.set(f'{router}/middlewares/1', f'{data["instance"]}-stripprefix')
    r.set(f'{router_s}/middlewares/1', f'{data["instance"]}-stripprefix')
else:
    r.delete(f'{middlewares}/{data["instance"]}-stripprefix/stripPrefix/prefixes/0')
    r.delete(f'{router}/middlewares/1')
    r.delete(f'{router_s}/middlewares/1')

# Mark route as user_created
if data.get('user_created') is not None and data["user_created"] is True:
    r.sadd(f'{agent_id}/user_created_routes', data["instance"])
else:
    r.srem(f'{agent_id}/user_created_routes', data["instance"])
    
# Setup forward route
if data.get("forward_auth"):
    r.set(f'{middlewares}/{data["instance"]}-auth/forwardAuth/address', f'{data["forward_auth"]["address"]}')
    r.set(f'{middlewares}/{data["instance"]}-auth/forwardAuth/tls/insecureSkipVerify', f'{data["forward_auth"].get("skip_tls_verify", False)}')
    r.set(f'{router}/middlewares/20', f'{data["instance"]}-auth')
    r.set(f'{router_s}/middlewares/20', f'{data["instance"]}-auth')
else:
    r.delete(f'{middlewares}/{data["instance"]}-auth/forwardAuth/address')
    r.delete(f'{middlewares}/{data["instance"]}-auth/forwardAuth/tls/insecureSkipVerify')
    r.delete(f'{router}/middlewares/20')
    r.delete(f'{router_s}/middlewares/20')

# Write the configuration on redis
r.execute()
